---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: microservices-poc
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-app
        image: microservicespoc.azurecr.io/helloworld-wimage:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
